### Simple DotNet Service - HTTP Requests & Integration Tests
### Test endpoints for the Outbound IP API

@dev_HostAddress = http://localhost:5000
@docker_HostAddress = http://localhost:8080
@baseUrl = {{dev_HostAddress}}

### Get outbound IP address
GET {{baseUrl}}/api/ip/outbound
Accept: application/json

> {%
client.test("Status code is 200", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Response has outboundip", function() {
  client.assert(response.body.hasOwnProperty("outboundip"), "Response does not have outboundip property");
});
%}

###

### Weather Forecast endpoint
GET {{baseUrl}}/weatherforecast
Accept: application/json

> {%
client.test("Weather Forecast Status code is 200", function() {
  client.assert(response.status === 200, "Weather forecast response status is not 200");
});
%}

###

### Swagger/OpenAPI Documentation
GET {{baseUrl}}/swagger/index.html
Accept: text/html

> {%
client.test("Swagger UI is accessible", function() {
  client.assert(response.status === 200, "Swagger UI is not accessible");
});
%}

###

### Test using Docker environment (uncomment @baseUrl and run)
# @baseUrl = {{docker_HostAddress}}
# GET {{baseUrl}}/api/ip/outbound
# Accept: application/json
#
# > {%
# client.test("Docker: Status code is 200", function() {
#   client.assert(response.status === 200, "Docker response status is not 200");
# });
# 
# client.test("Docker: outboundip is valid IP format", function() {
#   const jsonResponse = response.body;
#   const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
#   client.assert(ipRegex.test(jsonResponse.outboundip), "Docker outboundip is not a valid IP format");
# });
# %}
