name: Build and Deploy to Azure App Service

# This workflow runs on:
# - Pull requests to main (build and test only)
# - Pushes to main (build, test, and deploy to App Service)
# - Manual trigger via workflow_dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore simple-dotnet-service.sln
    
    - name: Build
      run: dotnet build simple-dotnet-service.sln --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test simple-dotnet-service.sln --no-build --verbosity normal --configuration Release
    
    - name: Publish
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: dotnet publish simple-dotnet-service.csproj --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Upload artifact for deployment
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-to-app-service:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Get App Service URL
      run: |
        echo "App Service URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "Test the API at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/ip/outbound"
