name: Build and Deploy Docker to Azure App Service

# This workflow runs on:
# - Pull requests to main (build, test, and Docker build - no push to registry)
# - Pushes to main (build, test, Docker build+push to ACR, and deploy to App Service)
# - Manual trigger via workflow_dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_CONTAINER_REGISTRY: simpledotnetregistry565.azurecr.io
  CONTAINER_NAME: simple-dotnet-service
  RESOURCE_GROUP: simple-dotnet-service-rg
  AZURE_WEBAPP_NAME: simple-dotnet-service

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore simple-dotnet-service.sln
    
    - name: Build
      run: dotnet build simple-dotnet-service.sln --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test simple-dotnet-service.sln --no-build --verbosity normal --configuration Release

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Azure using Managed Identity
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Log in to Azure Container Registry
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        az acr login --name simpledotnetregistry565
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:latest
          ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}

  deploy-to-app-service:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      id-token: write
    environment:
      name: 'production'
    
    steps:
    - name: Log in to Azure using Managed Identity
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy Docker image to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
    
    - name: Get App Service URL
      run: |
        WEBAPP_URL=$(az webapp show --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --query defaultHostName -o tsv)
        echo "App Service URL: https://${WEBAPP_URL}"
        echo "Test the API at: https://${WEBAPP_URL}/api/ip/outbound"
